version: '3.8'

services:
  DB:
    container_name: mysql
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: OutOfOfficeDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./DB/db_data:/var/lib/mysql